@extends('layouts.app')

@section('title')
    Test Series | View
@endsection

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

@section('content')
    <style>
        .question-bank-main-page {
            width: 100%;
            height: auto;
            display: grid;
            grid-template-columns: 1fr 2fr 1fr;
            gap: 10px
        }

        .button-actns-questn {
            text-align: center;
            padding: 107px 0;
        }

        .button-actns-questn i {
            display: block;
            width: 100%;
            padding: 10px;
            color: #fff;
        }

        .form-section {
            border: 1px solid #ccc;
            padding: 20px;
            border-radius: 7px;
        }

        label {
            font-weight: bold;
            margin-bottom: 5px;
        }

        input,
        select,
        textarea {
            width: 100%;
            padding: 8px;
            margin-bottom: 10px;
            border: 1px solid #ccc;
            border-radius: 4px;
        }

        .question-bank {
            display: flex;
            flex-direction: row;
            gap: 20px;
            border-top: 1px solid gray;
            margin-top: 30px;
            padding-top: 20px;
        }
    </style>

    <meta name="csrf-token" content="{{ csrf_token() }}">

    <div class="bg-light rounded">
        <div class="card">
            <div class="card-body">
                <div class="d-flex">
                    <div class="col">
                        <h5 class="card-title">{{ ucwords($test_series->title ?? "") }}</h5>
                        <h6 class="card-subtitle mb-2 text-muted">View Test Series section here.</h6>
                    </div>
                </div>

                <div class="mt-2">
                    @include('layouts.includes.messages')
                </div>

                <div class="mt-3 row">
                    <div class="col-md-4">
                        <p><strong>Title:</strong> {{ ucwords($test_series->title ?? "") }}</p>
                    </div>
                    <div class="col-md-4">
                        <p><strong>Language:</strong> {{ $test_series->language == 1 ? 'Hindi' : 'English' }}</p>
                    </div>
                    <div class="col-md-4">
                        <p><strong>Fee Type:</strong> {{ ucfirst($test_series->fee_type ?? "") }}</p>
                    </div>

                    <div class="col-md-4">
                        <p><strong>Commission:</strong> {{ $test_series->commission->name ?? '-' }}</p>
                    </div>
                    <div class="col-md-4">
                        <p><strong>Category:</strong> {{ $test_series->category->name ?? '-' }}</p>
                    </div>
                    <div class="col-md-4">
                        <p><strong>SubCategory:</strong> {{ $test_series->subcategory->name ?? '-' }}</p>
                    </div>

                    @if($test_series->fee_type == 'paid')
                        <div class="col-md-4">
                            <p><strong>MRP (₹):</strong> {{ $test_series->mrp }}</p>
                        </div>
                        <div class="col-md-4">
                            <p><strong>Discount (%):</strong> {{ $test_series->discount }}</p>
                        </div>
                        <div class="col-md-4">
                            <p><strong>Offered Price (₹):</strong> {{ $test_series->price }}</p>
                        </div>
                    @endif
                    <div class="col-md-4">
                        <p><strong>Test Type:</strong>
                            {{ isset($test_series->testseries[0]->type_name) ? $test_series->testseries[0]->type_name : '-' }}
                        </p>
                    </div>

                    <div class="col-md-4">
                        <p><strong>Test Generated By:</strong> {{ ucfirst($test_series->test_generated_by) }}</p>
                    </div>
                    <div class="col-md-4">
                        <p><strong>Total Papers:</strong> {{ $test_series->total_paper }}</p>
                    </div>

                    <div class="col-md-12 mt-3">
                        <p><strong>Short Description:</strong></p>
                        <div>{!! $test_series->short_description ?? '<em>No description provided</em>' !!}</div>
                    </div>
                    <div class="col-md-12 mt-3">
                        <p><strong>Description:</strong></p>
                        <div>{!! $test_series->description ?? '<em>No description provided</em>' !!}</div>
                    </div>

                    {{-- Show image/thumbnail if available --}}
                    @if(!empty($test_series->logo))
                        <div class="col-md-4 mt-3">
                            <p><strong>Thumbnail:</strong></p>
                            <img src="{{ asset('storage/' . $test_series->logo) }}" alt="Test Series Image" width="200"
                                class="rounded">
                        </div>
                    @endif

                    {{-- Test Paper Details --}}
                    @if(isset($test_series->testseries) && count($test_series->testseries) > 0)
                        <div class="col-md-12 mt-4">
                            <h4>Test Papers</h4>
                            <hr>
                            @foreach($test_series->testseries as $details)
                                </div>
                                <div class="col-md-12">
                                    <h5>{{ $details->test_paper_type ?? '' }} Paper</h5>
                                </div>

                                @php
                                    $relatedTests = $test_series->tests->where('id', $details->test_id);
                                @endphp


                                @foreach($relatedTests as $testpaper)
                                    @php
                                        $testDatas = json_decode($testpaper->question_marks_details, true);
                                        $mainIndex = 1;

                                    @endphp

                                    @if(!empty($testDatas))
                                        @foreach($testDatas as $key => $paper)
                                                @if(!empty($paper['sub_question_id']))
                                                    @php
                                                        $subquesDetails = Helper::getSubQuestionDetails(
                                                            $paper['sub_question_id'],
                                                            $paper['test_question_type'],
                                                            $paper['sub_negative_mark'],
                                                            $paper['sub_positive_mark']
                                                        );
                                                    @endphp
                                                    @include('test-series.sub-questions', [
                                                        'question' => $subquesDetails,
                                                        'marks' => $paper['sub_positive_mark'],
                                                        'index' => $key
                                                    ])
                                                 @else
                                                @php
                                                    $quesDetails = Helper::getQuestionDetails(
                                                        $paper['question_id'],
                                                        $paper['test_question_type'],
                                                        $paper['sub_negative_mark'],
                                                        $paper['positive_mark']
                                                    );
                                                @endphp
                                                        @include('test-series.questions', [
                                                            'question' => $quesDetails,
                                                            'marks' => $paper['positive_mark'],
                                                            'index' => $mainIndex
                                                        ])
                                                            @php $mainIndex++; @endphp
                                            @endif
                                        @endforeach
                                    @endif
                                @endforeach
                            @endforeach
                    @endif
                    </div>
                </div>
            </div>
        </div>
@endsection
